export const typesUI = {

    RADIO_BUTTON_UPDATE:  'RADIO_BUTTON_UPDATE',
    CONFIRM_POPUP_SHOW:   'CONFIRM_POPUP_SHOW',
    CONFIRM_POPUP_HIDE:   'CONFIRM_POPUP_HIDE',
    PAGINATION_UPDATE:    'PAGINATION_UPDATE',
    UNCHECK_CHILDREN:     'UNCHECK_CHILDREN',
    CHECKBOX_UPDATE:      'CHECKBOX_UPDATE',
    TEXTAREA_UPDATE:      'TEXTAREA_UPDATE',
    NUMBER_UPDATE:        'NUMBER_UPDATE',
    SWITCH_UPDATE:        'SWITCH_UPDATE',
    INPUT_UPDATE:         'INPUT_UPDATE',
    FORM_UPDATE:          'FORM_UPDATE',
    FORM_SUBMIT:          'FORM_SUBMIT',
    DATE_UPDATE:          'DATE_UPDATE',
    LOAD_DATA:            'LOAD_DATA',

  };
